#TRAVIS-CI setup for the Bingo Model package

language: php
php:
    - '5.6'
    - '7.0'
    - '7.1'
    - nightly

services:
    - mysql

before_install:
    - mysql -e "CREATE DATABASE dummy_data"

script: vendor/bin/phpunit -c phpunit.xml
